### ISSUE TITLE
Webview2.Winforms.DOM

### ISSUE THREAD

**Issue by pjacko** [ukandrewc/WebView2-DOM#1]
Hi Andrew,
I noticed you have moved from Webview2 to Chrome due to the privacy issues around MS. 
We were looking at using the WVBrowser for upgrading our old WebBrowser app.
However we are wondering what you are planning regarding the source code. 

Also I'm wondering if you are planning on doing a similar thing for the CEFSharp app?

regards,
Paul Jackson

**Comment by ukandrewc** [comment]
Apologies for letting you down on this, I just can't see how I could require users of WVBrowser to agree to the wording of the MS EULA.

Yes, I have moved to a CEFSharp version, which has moved a long a lot now. I am planning to make it a commercial product, but with reasonable pricing.

If you want to em me ukandrewc gmailcom, you're welcome to give it a try. I haven't really got time to set it up on GitHub at the moment.
